feat: add support for terraform v0.15
mineiros-io/terraform-github-organization pull request #30
Opened 2021-05-18 20:51 UTC by soerenmartius

2021-05-18 23:10 UTC, mariux requested changes

2021-05-18 23:10 UTC, mariux commented on examples/organization/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Please remove lock file

2021-05-20 08:41 UTC, soerenmartius commented on examples/organization/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
removed

2021-05-20 22:20 UTC, mariux requested changes

2021-05-20 22:20 UTC, mariux commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20|%200.13%20|%200.12.20+-623CE4.svg?logo=terraform
```suggestion
[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20|%200.14%20|%200.13%20|%200.12.20+-623CE4.svg?logo=terraform
```

2021-05-20 22:20 UTC, mariux commented on examples/organization/README.md
> +  version = "~> 0.5.0"
good catch ;)

2021-05-22 04:25 UTC, soerenmartius commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20|%200.13%20|%200.12.20+-623CE4.svg?logo=terraform
resolved in ec93e64

2021-05-22 14:06 UTC, mariux approved these changes
lgtm

2021-05-23 08:20 UTC, merged